apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-hero
  labels:
    name: nginx
    env: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
        env: prd
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          ports:
          - name: nginx-server
            containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-hero
  labels:
    name: nginx
    env: prd
spec:
  type: LoadBalancer
  ports:
  # the port that this service should serve on
  - port: 80
    targetPort: nginx-server
    nodePort: 30061
  selector:
    name: nginx
    env: prd
